openapi: 3.0.0
info:
  title: Hospital File Upload API
  version: 1.0.0
  description: API for uploading files, such as medical records, to the hospital system.
paths:
  /files/upload:
    post:
      summary: Upload a file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  fileId:
                    type: string
                    description: Unique identifier for the uploaded file
                  status:
                    type: string
                    description: Status of the upload
        '400':
          description: Invalid file upload request
