openapi: 3.0.3
info:
  title: "Hospital Room Availability API"
  version: "1.1"
  description: "This API retrieves information about room availability in the hospital."

tags:
  - name: RoomAvailabilityV1

paths:
  /rooms/availability:
    get:
      tags:
        - RoomAvailabilityV1
      operationId: getRoomAvailability
      description: |-
        <b>API Description :</b> Retrieves hospital room availability.<br/>
        <b>Security Level:</b> Level 2 (Authenticated, Token Required).<br/>
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomAvailabilityResponse"
        "404":
          description: Room information not found
        "500":
          description: Internal Server Error
      summary: Retrieve room availability information.

components:
  schemas:
    RoomAvailabilityResponse:
      type: object
      properties:
        roomId:
          type: integer
          description: Unique identifier for the room
        status:
          type: string
          description: Availability status of the room (e.g., available, occupied)
        type:
          type: string
          description: Type of room (e.g., single, double, ICU)
        floor:
          type: string
          description: Floor where the room is located
        description:
          type: string
          description: Additional details about the room
        lastCleaned:
          type: string
          format: date-time
          description: Date and time when the room was last cleaned
        nextAvailable:
          type: string
          format: date-time
          description: Date and time when the room will next be available
        currentPatientId:
          type: integer
          description: Unique identifier for the current patient in the room
        roomAttributes.*:
          type: string
          description: Dynamic attributes related to the room (e.g., bedCount, hasVentilator, hasOxygenSupply)
        assignedStaff:
          type: array
          description: List of staff assigned to the room
          items:
            type: object
            properties:
              staffId:
                type: integer
                description: Unique identifier for the staff member
              name:
                type: string
                description: Name of the staff member
              role:
                type: string
                description: Role of the staff member
              staffDetails.*:
                type: string
                description: Additional dynamic staff attributes (e.g., shiftTiming, specialization, yearsOfExperience)

