openapi: 3.0.3
info:
  title: "Patient Information API"
  version: "1.0"
  description: This API retrieves patient information from the hospital system.

tags:
  - name: PatientInfoV1

paths:
  /patients/{patientId}:
    get:
      tags:
        - PatientInfoV1
      operationId: getPatientInfo
      description: |-
        <b>API Description :</b> This API retrieves information for a specific patient by their ID.<br/>
        <b>Business Logic/Filter on data :</b> None<br/>
        <b>Source overview : </b> API Gateway>Database<br/>
        <b>Works with ''Try it Out''? :</b> Yes<br/>
        <b>Application Context/User Context/Both:</b> User Context<br/>
        <b>Caching and frequency :</b> None<br/>
        <b>Any exceptional scenarios associated to API?:</b> None<br/>
        <b>Security Level:</b> Level 2 (Authenticated)<br />
        <b>Hypermedia Links:</b> No<br /><b>Any exceptional scenarios associated to API?:</b> The API accepts the access token/apikey only in the header.<br/>
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: integer
          description: Unique identifier for the patient
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PatientInfoResponse"
        "404":
          description: Patient not found
        "406":
          description: Input data is in invalid format
        "500":
          description: Internal Server Error
      summary: This API retrieves patient information by patient ID.

components:
  schemas:
    PatientInfoResponse:
      description: Patient Information
      type: object
      properties:
        patientId:
          description: Unique identifier for the patient
          type: integer
        name:
          description: Name of the patient
          type: string
        dob:
          description: Date of birth of the patient
          type: string
          format: date
        gender:
          description: Gender of the patient
          type: string
        maritalStatus:
          description: Marital status of the patient
          type: string
        nationality:
          description: Nationality of the patient
          type: string
        occupation:
          description: Occupation of the patient
          type: string
        employer:
          description: Employer of the patient
          type: string
        bloodType:
          description: Blood type of the patient
          type: string
        organDonor:
          description: Organ donor status of the patient
          type: boolean
        primaryLanguage:
          description: Primary language spoken by the patient
          type: string
        secondaryLanguage:
          description: Secondary language spoken by the patient
          type: string
        religion:
          description: Religion of the patient
          type: string
        ethnicity:
          description: Ethnicity of the patient
          type: string
        contact:
          type: object
          properties:
            contact.phone:
              description: Phone number of the patient
              type: string
            contact.emails:
              type: array
              items:
                type: object
                properties:
                  contact.emailAddress:
                    description: Email address of the patient
                    type: string
                  contact.verified:
                    description: Whether the email address is verified
                    type: boolean
                  conatct.primary:
                    description: Indicates if the email is the primary contact email
                    type: boolean
                  contact.emailType:
                    description: Type of email (e.g., personal, work, other)
                    type: string
                  contact.emailDomain:
                    description: Domain of the email address
                    type: string
                  contact.emailCreationDate:
                    description: Creation date of the email address
                    type: string
                    format: date
                  contact.emailStatus:
                    description: Status of the email address (e.g., active, inactive)
                    type: string
                  contact.emailLastUpdated:
                    description: Last updated date of the email address
                    type: string
                    format: date
                  contact.emailOwner:
                    description: Owner of the email address
                    type: string
                  contact.emailProvider:
                    description: Email service provider
                    type: string
                  contact.emailPurpose:
                    description: Purpose of the email (e.g., personal, business)
                    type: string
                  contact.emailBackup:
                    description: Indicates if the email is a backup address
                    type: boolean
        address:
          type: object
          properties:
            street:
              description: Street address of the patient
              type: string
            city:
              description: City of the patient
              type: string
            state:
              description: State of the patient
              type: string
            zipCode:
              description: Zip code of the patient
              type: string
            country:
              description: Country of the patient
              type: string
        medicalHistory:
          type: array
          items:
            type: string
          description: List of medical history records for the patient
        allergies:
          type: array
          items:
            type: string
          description: List of allergies the patient has
