openapi: 3.0.3
info:
  title: "Patient Information API"
  version: "1.0"
  description: This API retrieves patient information from the hospital system.

tags:
  - name: PatientInfoV1

paths:
  /patients/{patientId}:
    get:
      tags:
        - PatientInfoV1
      operationId: getPatientInfo
      description: |-
        <b>API Description :</b> This API retrieves information for a specific patient by their ID.<br/>
        <b>Business Logic/Filter on data :</b> None<br/>
        <b>Source overview : </b> API Gateway>Database<br/>
        <b>Works with ''Try it Out''? :</b> Yes<br/>
        <b>Application Context/User Context/Both:</b> User Context<br/>
        <b>Caching and frequency :</b> None<br/>
        <b>Any exceptional scenarios associated to API?:</b> None<br/>
        <b>Security Level:</b> Level 2 (Authenticated)<br />
        <b>Hypermedia Links:</b> No<br /><b>Any exceptional scenarios associated to API?:</b> The API accepts the access token/apikey only in the header.<br/>
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: integer
          description: Unique identifier for the patient
      responses:
        "200":
          description: Patient information retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PatientInfoResponse"
        "404":
          description: Patient not found
        "406":
          description: Input data is in invalid format
        "500":
          description: Internal Server Error
      summary: This API retrieves patient information by patient ID.

components:
  schemas:
    PatientInfoResponse:
      description: Patient Information
      type: object
      properties:
        patientId:
          description: Unique identifier for the patient
          type: integer
        name:
          description: Name of the patient
          type: string
        dob:
          description: Date of birth of the patient
          type: string
          format: date
        contact:
          type: object
          properties:
            phone:
              description: Phone number of the patient
              type: string
            email:
              description: Email address of the patient
              type: string
        medicalHistory:
          type: array
          items:
            type: string
          description: List of medical history records for the patient
        address:
          type: object
          properties:
            street:
              description: Street address of the patient
              type: string
            city:
              description: City of the patient
              type: string
            state:
              description: State of the patient
              type: string
            zipCode:
              description: Zip code of the patient
              type: string
            country:
              description: Country of the patient
              type: string
        insurance:
          type: object
          properties:
            provider:
              description: Insurance provider of the patient
              type: string
            policyNumber:
              description: Insurance policy number of the patient
              type: string
            coverage:
              description: Coverage details of the patient's insurance
              type: string
        emergencyContact:
          type: object
          properties:
            name:
              description: Name of the emergency contact
              type: string
            relationship:
              description: Relationship to the patient
              type: string
            phone:
              description: Phone number of the emergency contact
              type: string
        allergies:
          type: array
          items:
            type: string
          description: List of allergies the patient has
        medications:
          type: array
          items:
            type: string
          description: List of medications the patient is currently taking
        surgeries:
          type: array
          items:
            type: object
          description: List of past surgeries
          properties:
            surgeryName:
              description: Name of the surgery
              type: string
            date:
              description: Date of the surgery
              type: string
              format: date
        immunizations:
          type: array
          items:
            type: object
          description: List of immunizations
          properties:
            immunizationName:
              description: Name of the immunization
              type: string
            date:
              description: Date of the immunization
              type: string
              format: date
        vitals:
          type: object
          properties:
            height:
              description: Height of the patient
              type: string
            weight:
              description: Weight of the patient
              type: string
            bloodPressure:
              description: Blood pressure of the patient
              type: string
            heartRate:
              description: Heart rate of the patient
              type: string
        physician:
          type: object
          properties:
            name:
              description: Name of the primary physician
              type: string
            contact:
              description: Contact details of the physician
              type: string
        insuranceExpiryDate:
          type: string
          format: date
          description: Expiry date of the patient's insurance policy
        registrationDate:
          type: string
          format: date
          description: Date of patient registration
        lastVisitDate:
          type: string
          format: date
          description: Date of the patient's last visit
