openapi: 3.0.3
info:
  title: "Prescription History API"
  version: "1.3"
  description: "This API retrieves a patient's prescription history, along with relevant healthcare details."

tags:
  - name: PrescriptionHistoryV1

paths:
  /prescriptions/history/{patientId}:
    get:
      tags:
        - PrescriptionHistoryV1
      operationId: getPrescriptionHistory
      description: |-
        <b>API Description :</b> Retrieves the prescription history of a specific patient.<br/>
        <b>Security Level:</b> Level 2 (Authenticated, Token Required).<br/>
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: integer
          description: Unique identifier for the patient
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PrescriptionHistoryResponse"
        "404":
          description: Patient not found
        "500":
          description: Internal Server Error
      summary: Retrieve prescription history by patient ID.

components:
  schemas:
    PrescriptionHistoryResponse:
      type: object
      properties:
        patientId:
          type: integer
          description: Unique identifier for the patient
        firstName:
          type: string
          description: First name of the patient
        lastName:
          type: string
          description: Last name of the patient
        dob:
          type: string
          format: date
          description: Date of birth of the patient
        gender:
          type: string
          enum: [Male, Female, Other]
        bloodType:
          type: string
          enum: [A+, A-, B+, B-, O+, O-, AB+, AB-]
          description: Blood type of the patient
        height:
          type: string
          description: Height of the patient (e.g., "5ft 8in" or "173cm")
        weight:
          type: string
          description: Weight of the patient (e.g., "70kg" or "154lbs")
        bmi:
          type: number
          format: float
          description: Body Mass Index (BMI)
        lifestyle:
          type: object
          properties:
            smoker:
              type: boolean
              description: Whether the patient is a smoker
            alcoholConsumption:
              type: string
              enum: [None, Light, Moderate, Heavy]
              description: Patient’s alcohol consumption level
            physicalActivity:
              type: string
              enum: [Sedentary, Low, Moderate, High]
              description: Patient's physical activity level
        contact:
          type: object
          properties:
            homePhone:
              type: string
              description: Patient's home phone number
            workPhone:
              type: string
              description: Patient's work phone number
            emergencyContact:
              type: object
              properties:
                name:
                  type: string
                  description: Name of emergency contact
                relation:
                  type: string
                  description: Relationship with patient (e.g., spouse, parent)
                phone:
                  type: string
                  description: Emergency contact number
            email:
              type: string
              description: Email address of the patient
        insurance:
          type: object
          properties:
            provider:
              type: string
              description: Name of the insurance provider
            policyNumber:
              type: string
              description: Insurance policy number
            coverageDetails:
              type: string
              description: Summary of insurance coverage
            expiryDate:
              type: string
              format: date
              description: Expiration date of the insurance policy
        medicalHistory:
          type: object
          properties:
            allergies:
              type: array
              items:
                type: string
              description: List of known allergies
            chronicConditions:
              type: array
              items:
                type: string
              description: List of chronic medical conditions
            pastSurgeries:
              type: array
              items:
                type: string
              description: List of past surgeries undergone by the patient
            familyHistory:
              type: array
              items:
                type: string
              description: Family medical history (e.g., Diabetes, Heart Disease)
        vitals:
          type: object
          properties:
            bloodPressure:
              type: string
              description: Blood pressure reading (e.g., "120/80 mmHg")
            heartRate:
              type: integer
              description: Heart rate in beats per minute
            oxygenSaturation:
              type: integer
              description: Oxygen saturation percentage (e.g., 98%)
            glucoseLevel:
              type: number
              format: float
              description: Blood glucose level (mg/dL)
        prescriptions:
          type: array
          items:
            type: object
            properties:
              prescriptionId:
                type: integer
                description: Unique identifier for the prescription
              medication:
                type: object
                properties:
                  genericName:
                    type: string
                    description: Generic name of the medication
                  brandName:
                    type: string
                    description: Brand name of the medication
                  form:
                    type: string
                    description: Form of the drug (tablet, capsule, injection)
                  strength:
                    type: string
                    description: Strength of the medication (e.g., 500mg, 10mL)
              dosage:
                type: string
                description: Dosage of the medication
              frequency:
                type: string
                description: Frequency of the medication (e.g., once daily)
              route:
                type: string
                description: Method of administration (e.g., oral, intravenous)
              sideEffects:
                type: array
                items:
                  type: string
                description: List of common side effects
              drugInteractions:
                type: array
                items:
                  type: string
                description: List of drugs that may interact negatively
              startDate:
                type: string
                format: date
                description: Start date of the prescription
              endDate:
                type: string
                format: date
                description: End date of the prescription
              prescribingDoctor:
                type: string
                description: Name of the prescribing doctor
              prescribingDepartment:
                type: string
                description: Hospital department that issued the prescription
              notes:
                type: string
                description: Additional notes about the prescription
              refillStatus:
                type: string
                enum: [Not Refillable, Refillable, Completed]
                description: Status of the prescription refill
              refillCount:
                type: integer
                description: Number of refills allowed
              lastRefillDate:
                type: string
                format: date
                description: Last refill date
              pharmacyDetails:
                type: object
                properties:
                  pharmacyName:
                    type: string
                    description: Name of the pharmacy
                  pharmacyContact:
                    type: string
                    description: Contact number of the pharmacy
                  pharmacyAddress:
                    type: string
                    description: Address of the pharmacy
                  licenseNumber:
                    type: string
                    description: License number of the pharmacy
                  openingHours:
                    type: string
                    description: Operating hours of the pharmacy
                  deliveryAvailable:
                    type: boolean
                    description: Whether the pharmacy offers home delivery
                  pharmacistInCharge:
                    type: string
                    description: Name of the pharmacist in charge
