openapi: 3.0.3
info:
  title: "Prescription History API"
  version: "1.2"
  description: "This API retrieves the prescription history of a patient from the hospital system."

tags:
  - name: PrescriptionHistoryV1

paths:
  /prescriptions/history/{patientId}:
    get:
      tags:
        - PrescriptionHistoryV1
      operationId: getPrescriptionHistory
      description: |-
        <b>API Description :</b> Retrieves the prescription history of a specific patient by their ID.<br/>
        <b>Security Level:</b> Level 2 (Authenticated, Token Required).<br/>
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: integer
          description: Unique identifier for the patient
        - name: firstName
          in: query
          required: false
          schema:
            type: string
          description: First name of the patient (optional)
        - name: lastName
          in: query
          required: false
          schema:
            type: string
          description: Last name of the patient (optional)
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PrescriptionHistoryResponse"
        "404":
          description: Patient not found
        "500":
          description: Internal Server Error
      summary: Retrieve prescription history by patient ID.

components:
  schemas:
    PrescriptionHistoryResponse:
      type: object
      properties:
        patientId:
          type: integer
          description: Unique identifier for the patient
        firstName:
          type: string
          description: First name of the patient
        lastName:
          type: string
          description: Last name of the patient
        dob:
          type: string
          format: date
          description: Date of birth of the patient
        gender:
          type: string
          enum: [Male, Female, Other]
        contact:
          type: object
          properties:
            homePhone:
              type: string
              description: Patient's home phone number
            workPhone:
              type: string
              description: Patient's work phone number
            emergencyContact:
              type: object
              properties:
                name:
                  type: string
                  description: Name of emergency contact
                relation:
                  type: string
                  description: Relationship with patient (e.g., spouse, parent)
                phone:
                  type: string
                  description: Emergency contact number
            primaryPhysician:
              type: string
              description: Name of the primary care physician
            primaryPhysicianPhone:
              type: string
              description: Contact number of the primary physician
            email:
              type: string
              description: Email address of the patient
        insurance:
          type: object
          properties:
            provider:
              type: string
              description: Name of the insurance provider
            policyNumber:
              type: string
              description: Insurance policy number
            coverageDetails:
              type: string
              description: Summary of insurance coverage
            expiryDate:
              type: string
              format: date
              description: Expiration date of the insurance policy
        medicalHistory:
          type: object
          properties:
            allergies:
              type: array
              items:
                type: string
              description: List of known allergies
            chronicConditions:
              type: array
              items:
                type: string
              description: List of chronic medical conditions
        appointments:
          type: object
          properties:
            upcoming:
              type: object
              properties:
                date:
                  type: string
                  format: date
                  description: Date of next appointment
                doctor:
                  type: string
                  description: Name of the doctor for next appointment
                reason:
                  type: string
                  description: Reason for the appointment
        prescriptions:
          type: array
          description: List of prescriptions
          items:
            type: object
            properties:
              prescriptionId:
                type: integer
                description: Unique identifier for the prescription
              medication:
                type: object
                properties:
                  genericName:
         
