openapi: 3.0.3
info:
  title: "Prescription History API"
  version: "1.0"
  description: This API retrieves the prescription history of a patient from the hospital system.

tags:
  - name: PrescriptionHistoryV1

paths:
  /prescriptions/history/{patientId}:
    get:
      tags:
        - PrescriptionHistoryV1
      operationId: getPrescriptionHistory
      description: |-
        <b>API Description :</b> This API retrieves the prescription history of a specific patient by their ID.<br/>
        <b>Business Logic/Filter on data :</b> None<br/>
        <b>Source overview : </b> API Gateway>Database<br/>
        <b>Works with ''Try it Out''? :</b> Yes<br/>
        <b>Application Context/User Context/Both:</b> User Context<br/>
        <b>Caching and frequency :</b> None<br/>
        <b>Any exceptional scenarios associated to API?:</b> The API accepts the access token/apikey only in the header.<br/>
        <b>Security Level:</b> Level 2 (Authenticated)<br/>
        <b>Hypermedia Links:</b> No<br/>
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: integer
          description: Unique identifier for the patient
        - name: firstName
          in: query
          required: false
          schema:
            type: string
          description: First name of the patient (optional)
        - name: lastName
          in: query
          required: false
          schema:
            type: string
          description: Last name of the patient (optional)
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PrescriptionHistoryResponse"
        "404":
          description: Patient not found
        "406":
          description: Input data is in invalid format
        "500":
          description: Internal Server Error
      summary: Retrieve prescription history by patient ID.

components:
  schemas:
    PrescriptionHistoryResponse:
      description: Prescription History
      type: object
      properties:
        patientId:
          description: Unique identifier for the patient
          type: integer
        prescriptions:
          type: array
          description: List of prescriptions
          items:
            type: object
            properties:
              prescriptionId:
                description: Unique identifier for the prescription
                type: integer
              medication:
                description: Name of the medication
                type: string
              dosage:
                description: Dosage of the medication
                type: string
              frequency:
                description: Frequency of the medication
                type: string
              startDate:
                description: Start date of the prescription
                type: string
                format: date
              endDate:
                description: End date of the prescription
                type: string
                format: date
              prescribingDoctor:
                description: Doctor who prescribed the medication
                type: string
              notes:
                description: Additional notes about the prescription
                type: string
